### ISSUE TITLE
Create layout of signup page

### ISSUE THREAD

**Issue by anynikulina** [Project-U-Development/refund-tracker.github.io#18]
This task is only about placing components as in design. No form functionality yet.

**Acceptance criteria:**

- html page with components

**Comment by TatianaBortnik** [comment]
The page should contain:

- Name/Login input;
- Email input;
- Password input;
- "Create login" primary button;
- Link to login page

Page example: https://cdn.vectorstock.com/i/1000x1000/52/62/sign-up-page-purple-gradient-registration-form-vector-23745262.webp
