### ISSUE TITLE
Create layout of Forget password page

### ISSUE THREAD

**Issue by anynikulina** [Project-U-Development/refund-tracker.github.io#19]
This task is only about placing components as in design. No form functionality yet.

**Acceptance criteria:**

- html page with components

**Comment by TatianaBortnik** [comment]
Layout depends on functionality. There are some variants.

1. User enter email and application sends user password on this email. The bad one - password should be saved in encripted form. 
2. User enter email, application create new password and send it on email. So there should be additional form where user could change password.
3. User enter email, application sends confirmation code, user enter confirmation code and new password. 

Page example https://i.ytimg.com/vi/IpznmyXApms/maxresdefault.jpg
