### ISSUE TITLE
Datepicker: highlight selected date in calendar

### ISSUE THREAD

**Issue by tbazko** [Project-U-Development/refund-tracker.github.io#36]
AC:
* After date is selected, it stays highlighted in calendar
* If date was manually typed in datepicker input, it also becomes highlighted in calendar

**Comment by OlenaZH84** [comment]
split the task into two separate tasks:
After date is selected, it stays highlighted in calendar - done
If date was manually typed in datepicker input, it also becomes highlighted in calendar - new task #79
