### ISSUE TITLE
Create a Sign Up endpoint

### ISSUE THREAD

**Issue by anynikulina** [Project-U-Development/refund-tracker.github.io#50]
**Acceptance Criteria:**

POST request which stores new user to DB
Body of request should contain unique email and password (no patterns)

**Comment by vikawal** [comment]
As variant:
const app = require('fastify')
const bcrypt = require('bcrypt')
const mysql = require('mysql2')

const connection = mysql.createPool({
  host: 'localhost',
  user: 'root',
  password: '',
  database: 'mydb',
});

async function checkEmailExists(email, connection) {
  const [results] = await connection.execute(`SELECT * FROM users WHERE email = '${email}'`);
   if (results.length > 0) {
    return true;
  } else {
    return false;
  }
}

async function hashPassword(password) {
  const saltRounds = 10;
  const hashedPassword = await bcrypt.hash(password, saltRounds);
  return hashedPassword;
}

app.post('/register', async (req, res) => {
  const email = req.body.email;
  const password = req.body.password;

 // check if email and password were provided
  if (!email || !password) {
    return res.status(400).send({ error: 'Please provide both email and password' })
  }
// if email exists
const exists = await checkEmailExists(email, connection);
  if (exists) {
    return res.status(400).send({ error: 'This email is already registered' });
  } else {
    try {
      const hashedPassword = await hashPassword(password);
      await connection.execute(`INSERT INTO users (email, password) VALUES ('${email}', '${hashedPassword}')`);
      return res.status(201).send({ message: 'User registered successfully' });
    } catch (err) {
      console.error(err);
      return res.status(500).send({ error: 'An error occurred while registering the user' });
    }
  }
});
