### ISSUE TITLE
Check if user exists

### ISSUE THREAD

**Issue by anynikulina** [Project-U-Development/refund-tracker.github.io#57]
AC:

Before creating a user check if user already exists
In case of existing user response with an error (code TBD)

**Comment by vikawal** [comment]
async function checkEmailExists(email, connection) {
  const [results] = await connection.execute(`SELECT * FROM users WHERE email = '${email}'`);
  if (results.length > 0) {
    return true;
  } else {
    return false;
  }
}

Can be used and in log in and in register:

app.post('/login', async (req, res) => {
  const email = req.body.email;
  const exists = await checkEmailExists(email, connection);
  if (exists) {
    // check password and return appropriate response
  } else {
    return res.status(400).send({ error: 'This email is not registered' });
  }
});

app.post('/register', async (req, res) => {
  const email = req.body.email;
  const exists = await checkEmailExists(email, connection);
  if (exists) {
    return res.status(400).send({ error: 'This email is already registered' });
  } else {
    // register the user
  }
});
