### ISSUE TITLE
UI: Input

### ISSUE THREAD

**Issue by tbazko** [Project-U-Development/refund-tracker.github.io#6]
Create component **Input**:
1. Create a field for input text.
2. Create a field for the input number.
3. To implement a change in the color of the field selection when focusing on the field.

The **Input**  should consist of fieldset that contain a label and an input box placed one under the other (label first).
The **Input** should have a border with radius 8px.

_Inactive **Input**_ 
border: 1px solid #CCDFFF;
![Image](https://user-images.githubusercontent.com/10188652/194662460-8319ab47-be0a-4147-b148-a69c4471009e.png)

_Focused **Input**_ 
border: 3px solid #00E4CA;
![Image](https://user-images.githubusercontent.com/10188652/194662635-530d4311-6bec-408b-95a9-8dfe2524a843.png)

_Attributes for label:_
  font-weight: 600;
  font-size: 14px;
  line-height: 16px;
  display: flex;
  align-items: center;
  color: #0061FF;

Input box (as the part of **Input** component) shouldn`t have borders both in focused and inactive states.
Input box should have placeholder: "Text" for text input, "Number" for number input.
_Attributes for placeholder:_
  font-weight: 300;
  font-size: 18px;
  line-height: 28px;
  color: #9999B1;
_Attributes of input field text:_
  font-weight: 600;
  font-size: 18px;
  line-height: 28px;
  color: #00003C;

When input box is filled with data the check mark should appear near right border of **Input** component.

_Input filled with data_

![Image](https://user-images.githubusercontent.com/10188652/194662710-00daa084-8478-4b07-a344-6a332c2ca8cf.png)

**Comment by TatianaBortnik** [comment]
Question 1.
Should we provide validation rules for text input or this is an issue of developer?
