### ISSUE TITLE
Expand dropdown on click anywhere within the element

### ISSUE THREAD

**Issue by artembykov** [Project-U-Development/refund-tracker.github.io#74]
Currently only the arrow button (`.select-button`) expands dropdown when clicked. Need to enable clicks anywhere **within** the element (`.select-block`).

<img width="317" alt="Screenshot 2023-01-12 at 23 16 31" src="https://user-images.githubusercontent.com/426560/212192881-dd780567-148f-42f7-9e23-3a85081c84e4.png">

**Comment by OlenaZH84** [comment]
done
