### ISSUE TITLE
UI: Datepicker

### ISSUE THREAD

**Issue by tbazko** [Project-U-Development/refund-tracker.github.io#8]
You will implement the ability to work with the calendar 

![Image](https://user-images.githubusercontent.com/108478832/194720997-d970d0b8-a313-495e-8aba-c13eced69393.png)

You have to create the field to enter a date in a format DD.MM.YYYY (you can have a look the description of calendar functionality).

The description of calendar functionality:

1. Сreate an event to implement automatic filling of the current date with the possibility to change it.

2. To implement the event change:
- the the year selection;
- the month selection;
- the date selection.

You need to clarify the checkpoints of the possibility of change???

3. Description of the calendar block:
- The calendar block consists of a header and a scrollable area with a calendar grid. When the cursor is over the calendar grid, the main scrolling of the page is blocked.
- The title shows the name of the current date with the possibility to change it.
- The calendar block "follows" the value in the field: the month was changed from the keyboard - the calendar scrolled to the corresponding date.
- The selected day is highlighted with a gray circle.

4. To implement the event reminders via e-mail (sms / viber). You need to clarify the necessity of this function???
Description of checks:

- Is it necessary to limit the date selection???
- Is it possibility field filling from the current date???

**Should I describe the input of the value from the keyboard?**

**Comment by Elena17T** [comment]
Can you explain please what does it means : "You need to clarify the checkpoints of the possibility of change" ?

**Comment by alamusienko** [comment]
https://github.com/Project-U-Development/refund-tracker.github.io/issues/8#issuecomment-1310509331 
This question is relevant when we will be the requirements described for working with web forms

**Comment by Elena17T** [comment]
#8(comment) 
So why this task is number two in our list of tasks?
